
[general]
import = ["/home/D35IRE/.cache/wal/colors-alacritty.toml"] # like your wal integration

[window]
opacity = 0.15
startup_mode = "Windowed"
padding = { x = 8, y = 8 }
dynamic_padding = true
decorations = "buttonless"
blur = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12.0

[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true

[terminal.shell]
program = "/bin/zsh"

[keyboard]
# Copy (Ctrl+C won’t override SIGINT here)
bindings = [
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "PageUp", action = "ScrollPageUp" },
  { key = "PageDown", action = "ScrollPageDown" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Plus", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" }
]
  
[terminal]
# Bracketed paste support (prevents command injection when pasting)
osc52 = "OnlyCopy"


[colors]
draw_bold_text_with_bright_colors = true
